### ISSUE TITLE
Does not work on babel >= 6.0

### ISSUE THREAD

**Issue by nicksrandall** [codemix/babel-plugin-closure-elimination#3]
```
ERROR in ./common/index.js
Module build failed: TypeError: Transformer is not a function
    at build (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-plugin-closure-elimination/lib/index.js:153:10)
    at Function.memoisePluginContainer (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:127:13)
    at Function.normalisePlugin (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:161:32)
    at /Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.init (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-loader/index.js:14:22)
    at /Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-loader/lib/fs-cache.js:140:16
    at ReadFileContext.callback (/Users/nicksrandall/Documents/DomoGithub/AppTeam6/da-webpack/node_modules/babel-loader/lib/fs-cache.js:27:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:325:13)
```

**Comment by phpnode** [comment]
Not yet. I plan to support it, I just haven't had time yet. PRs welcome :)

**Comment by jadbox** [comment]
+1 (wish I had time to fix this)

**Comment by jadbox** [comment]
I've updated the tests and build scripts to use Babel 6 in my branch below. However, I do not know enough about Babel 6 to determine how to replace the use of Transformer in src/index.js as it's no longer part of the entry parameters given to the plugin by Babel. *

https://github.com/jadbox/babel-plugin-closure-elimination

**
```
http://babeljs.io/blog/2015/10/29/6.0.0/
Babel 5

export default function({ Plugin, types: t }) {
  return new Plugin(‘ast-transform’, {
    visitor: { … }
  });
}
Babel 6

export default function({ types: t }) {
  return {
    visitor: { … }
  };
}
```

**Comment by develar** [comment]
@phpnode Does it mean that you found this plugin useless and don't want to develop/use it anymore?

**Comment by phpnode** [comment]
@develar not at all, the project that I wrote this for is still on babel 5 and I've not had chance to upgrade it yet. I'd like to use this on my babel 6 projects too but there are only so many hours in the day and those are not as performance sensitive - PRs are welcome, otherwise I will get around to this in the coming weeks / months.

**Comment by develar** [comment]
@phpnode Thanks for clarification. I am interested because I want to debug lambdas and it is not possible since V8 VM doesn't support column-based breakpoints correctly in all cases (https://bugs.chromium.org/p/v8/issues/detail?id=2825). (I develop JetBrains JS debugger (WebStorm, IDEA and so on)).

**Comment by Gvozd** [comment]
Good news everyone!
https://github.com/codemix/babel-plugin-closure-elimination/pull/4

I finish work of @jadbox

**Comment by phpnode** [comment]
![image](https://cloud.githubusercontent.com/assets/363611/12576452/a3de2d3a-c40b-11e5-9e2f-9b03192dd666.png)

awesome work @Gvozd

**Comment by phpnode** [comment]
Fixed in 1.0.0

**Comment by jadbox** [comment]
@Gvozd Thanks so much finishing the work in my branch! I'm excited to see if this improves performance.

Btw, will this work for => functions?
